# Generated by Django 5.1.7 on 2026-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('BORRADOR', 'Borrador'), ('MAS65', 'Mayor o igual 65'), ('OA_MENOS65', 'OA menor 65'), ('HOMBROS', 'Hombros'), ('LUMBAGOS', 'Lumbagos'), ('SDNT', 'SDNT'), ('SDT', 'SDT'), ('OTROS_NEUROS', 'Otros neuros'), ('AATT', 'AATT'), ('DUPLA', 'Dupla')], max_length=20)),
                ('diagnostico', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['categoria', 'diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ccr', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('fecha_derivacion', models.DateField()),
                ('percapita_desde', models.CharField(blank=True, max_length=150)),
                ('nombre', models.CharField(max_length=160)),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('edad', models.PositiveIntegerField()),
                ('diagnostico', models.TextField()),
                ('profesional', models.CharField(max_length=160)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIANA', 'Mediana'), ('MODERADA', 'Moderada'), ('LICENCIA_MEDICA', 'Licencia Medica')], max_length=20)),
                ('categoria', models.CharField(choices=[('BORRADOR', 'Borrador'), ('MAS65', 'Mayor o igual 65'), ('OA_MENOS65', 'OA menor 65'), ('HOMBROS', 'Hombros'), ('LUMBAGOS', 'Lumbagos'), ('SDNT', 'SDNT'), ('SDT', 'SDT'), ('OTROS_NEUROS', 'Otros neuros'), ('AATT', 'AATT'), ('DUPLA', 'Dupla')], max_length=20)),
                ('mayor_60', models.BooleanField(default=False, editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INGRESADO', 'Ingresado'), ('RESCATE', 'Rescate'), ('ABANDONO', 'Abandono'), ('ALTA_MEDICA', 'Alta medica'), ('EGRESO_VOLUNTARIO', 'Egreso voluntario'), ('DERIVADO', 'Derivado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_cambio_estado', models.DateTimeField(auto_now_add=True)),
                ('n_intentos_contacto', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_derivacion', '-id'],
            },
        ),
    ]
