# Generated by Django 5.1.7 on 2026-04-15 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientopaciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='kine_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['rut', 'fecha_derivacion'], name='pacientes_p_rut_98796c_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['categoria'], name='pacientes_p_categor_75b619_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['prioridad'], name='pacientes_p_priorid_51b67a_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='pacientes_p_estado_8c5b22_idx'),
        ),
    ]
