# Generated by Django 5.1.7 on 2026-04-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar', '0003_alter_importacionmensual_options_and_more'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='paciente',
            name='importacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_creados', to='importar.importacionmensual'),
        ),
    ]
