# Generated by Django 5.1.7 on 2026-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_add_contact_and_appointment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='proxima_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
