# Generated by Django 5.1.7 on 2026-04-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_add_proxima_atencion_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='n_meses_espera',
            field=models.PositiveIntegerField(default=1, help_text='Veces que ha aparecido en listas mensuales'),
        ),
    ]
