# Generated by Django 5.1.7 on 2026-04-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar', '0003_alter_importacionmensual_options_and_more'),
        ('pacientes', '0006_paciente_n_meses_espera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='importacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to='importar.importacionmensual'),
        ),
    ]
