# Generated by Django 5.1.7 on 2026-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_importados', models.PositiveIntegerField(default=0)),
                ('errores', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-fecha_subida', '-id'],
            },
        ),
    ]
