# Generated by Django 5.1.7 on 2026-04-16 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacionmensual',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.RenameField(
            model_name='importacionmensual',
            old_name='usuario_subio',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='anio_datos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='archivo_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='duplicados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='estado',
            field=models.CharField(choices=[('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('REEMPLAZADO', 'Reemplazado'), ('CON_ERRORES', 'Con errores')], default='COMPLETADO', max_length=20),
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='mes_datos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacionmensual',
            name='reemplazada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='importar.importacionmensual'),
        ),
    ]
